@startuml
' http://plantuml.com/preprocessing
' include

'!include https://raw.githubusercontent.com/Clicketyclick/TipsAndTricks/master/test/List.iuml
!include ./List.iuml
!plantuml::List.iuml[].
List <|.. ArrayList
@enduml
