@startuml
' http://plantuml.com/preprocessing
' include

title
Read from file %filename%
Path is %dirpath%
end title

'Title dir[%dirpath()] file[%filename()]

'!include https://raw.githubusercontent.com/Clicketyclick/TipsAndTricks/master/test/List.iuml
'!include ./List.iuml
'!plantuml::List.iuml[].
List <|.. ArrayList

'List -> ArrayList: %dirpath()

@enduml
